language: java
sudo: false
script: "mvn clean verify"
script: "docker-compose up"
script: "docker login -u dockerHubLogin -p dockerHubPass"
script: "docker push dockerHubLogin/tp2_db"
script: "docker push dockerHubLogin/tp2_api"
