language: java
sudo: false
script: 
    - "mvn clean verify"
    - "docker build -t dockerHubLogin/api ./sample-application-http-api-server"
    - "docker build -t dockerHubLogin/db ./sample-application-db-changelog-job"
    - "docker login -u dockerHubLogin -p dockerHubPass"
    - "docker push dockerHubLogin/tp2_db"
    - "docker push dockerHubLogin/tp2_api"
